[package]
name = "min_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.0.3", default-features = false, features = ["postgres", "chrono"] }
dotenvy = "0.15.7"
